{
  :Moderna : {
               :params : Vaccineparams(
                           name=:Moderna,
                           reqdshots=2,
                           delay2ndshot=21,
                           halflife=280,
                           infectreduce={
                                           :first : {:alpha : 0.92, 
                                                     :base : 0.92, 
                                                     :delta : 0.85},
                                           :full : {:alpha : 0.95, 
                                                    :base : 0.95, 
                                                    :delta : 0.88},
                                           :booster : {:alpha : 0.95, 
                                                       :base : 0.95, 
                                                       :delta : 0.88},
                                         },
                           full_effect_days=14,
                           day1_effect=0.5,
                           infectfactor=0.75,
                         ),
             },
  :Pfizer : {
              :params : Vaccineparams(
                          name=:Pfizer,
                          reqdshots=2,
                          delay2ndshot=21,
                          halflife=280,
                          infectreduce={
                                          :first : {:alpha : 0.9, 
                                                    :base : 0.9, 
                                                    :delta : 0.84},
                                          :full : {:alpha : 0.94, 
                                                   :base : 0.94, 
                                                   :delta : 0.88},
                                          :booster : {:alpha : 0.94, 
                                                      :base : 0.94, 
                                                      :delta : 0.88},
                                        },
                          full_effect_days=14,
                          day1_effect=0.5,
                          infectfactor=0.75,
                        ),
            },
  :JnJ : {
           :params : Vaccineparams(
                       name=:JnJ,
                       reqdshots=1,
                       delay2ndshot=0,
                       halflife=240,
                       infectreduce={
                                       :first : {:alpha : 0.88, 
                                                 :base : 0.88, 
                                                 :delta : 0.8},
                                       :full : {:alpha : 0.88, 
                                                :base : 0.88, 
                                                :delta : 0.8},
                                       :booster : {:alpha : 0.88, 
                                                   :base : 0.88, 
                                                   :delta : 0.8},
                                     },
                       full_effect_days=14,
                       day1_effect=0.5,
                       infectfactor=0.75,
                     ),
         },
}
